# Generated by Django 4.2.6 on 2023-10-06 00:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APIProjetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagemrotulada',
            unique_together={('projeto', 'rotulo', 'imagem')},
        ),
        migrations.AlterUniqueTogether(
            name='projeto',
            unique_together={('usuario', 'titulo')},
        ),
    ]
