# Generated by Django 4.2.6 on 2023-10-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjetos', '0002_alter_imagemrotulada_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotulo',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
