# Generated by Django 4.2.6 on 2023-10-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjetos', '0003_alter_rotulo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotulo',
            name='projetos',
            field=models.ManyToManyField(related_name='rotulos', to='APIProjetos.projeto'),
        ),
    ]
