# Generated by Django 4.2.6 on 2023-10-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjetos', '0005_alter_imagemrotulada_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='imagemrotulada',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='rotulo',
            name='ativo',
        ),
    ]
