# Generated by Django 4.2.6 on 2023-10-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjetos', '0006_remove_imagem_ativo_remove_imagemrotulada_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemrotulada',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='APIProjetos.imagem'),
        ),
    ]
