# Generated by Django 4.2.6 on 2023-10-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjetos', '0007_alter_imagemrotulada_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemrotulada',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotulos', to='APIProjetos.imagem'),
        ),
        migrations.AlterField(
            model_name='imagemrotulada',
            name='rotulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='APIProjetos.rotulo'),
        ),
    ]
