# Generated by Django 4.2.6 on 2023-10-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjetos', '0009_alter_imagemrotulada_rotulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemrotulada',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagensrotuladas', to='APIProjetos.imagem'),
        ),
    ]
