# Generated by Django 4.2.6 on 2023-10-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjetos', '0013_alter_rotulo_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='teste',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='treino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
