# Generated by Django 4.2.6 on 2023-10-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjetos', '0014_projeto_teste_projeto_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='teste',
            field=models.DecimalField(blank=True, decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='treino',
            field=models.DecimalField(blank=True, decimal_places=2, default=70.0, max_digits=5),
        ),
    ]
