# Generated by Django 4.2.6 on 2023-10-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjetos', '0015_alter_projeto_teste_alter_projeto_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='imagens/'),
        ),
    ]
