# Generated by Django 4.2.6 on 2023-10-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjetos', '0017_projeto_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemrotulada',
            name='treino',
            field=models.BooleanField(default=False),
        ),
    ]
